### ISSUE TITLE
Exception in thread "Thread-1" java.lang.UnsatisfiedLinkError:  Run s2pc-aby SingleZ2cTest

### ISSUE THREAD

**Issue by zhangyingjie7** [alibaba-edu/mpc4j#18]
您好，

我在学习您们团队的mpc4j代码，在运行s2pc-aby中的SingleZ2cTest 时，出现如下错误

Exception in thread "Thread-1" java.lang.UnsatisfiedLinkError: 'byte[] edu.alibaba.mpc4j.common.tool.crypto.ecc.fourq.FourqByteFullEcc.nativeMul(byte[], byte[])'
	at edu.alibaba.mpc4j.common.tool.crypto.ecc.fourq.FourqByteFullEcc.nativeMul(Native Method)
	at edu.alibaba.mpc4j.common.tool.crypto.ecc.fourq.FourqByteFullEcc.mul(FourqByteFullEcc.java:111)
	at edu.alibaba.mpc4j.s2pc.pcg.ot.base.np01.Np01ByteBaseOtSender.generateInitPayload(Np01ByteBaseOtSender.java:88)
	at edu.alibaba.mpc4j.s2pc.pcg.ot.base.np01.Np01ByteBaseOtSender.send(Np01ByteBaseOtSender.java:58)
	at edu.alibaba.mpc4j.s2pc.pcg.ot.cot.core.alsz13.Alsz13CoreCotReceiver.init(Alsz13CoreCotReceiver.java:61)
	at edu.alibaba.mpc4j.s2pc.pcg.ot.cot.nc.ywl20.Ywl20NcCotReceiver.init(Ywl20NcCotReceiver.java:96)
	at edu.alibaba.mpc4j.s2pc.pcg.ot.cot.impl.cache.CacheCotReceiver.init(CacheCotReceiver.java:71)
	at edu.alibaba.mpc4j.s2pc.aby.basics.z2.rrg21.Rrg21Z2cReceiver.init(Rrg21Z2cReceiver.java:63)
	at edu.alibaba.mpc4j.s2pc.aby.basics.z2.SingleDyadicZ2cReceiverThread.run(SingleDyadicZ2cReceiverThread.java:79)

![image](https://github.com/alibaba-edu/mpc4j/assets/24225846/147cfb49-2836-4f70-b1c3-cc654d2c8ff5)

运行其他-s2pc-的文件，也会出现类似错误。运行-common-的测试文件不会出现类似错误。

我的电脑配置为：
```
java version "17.0.5" 2022-10-18 LTS
Darwin Kernel Version 22.6.0:RELEASE_ARM64_T6000 arm64
```

麻烦您帮我看一下，非常感谢🙏

**Comment by liuweiran900217** [comment]
你好！如果你成功编译成功了mpc4j-native-tool，且mpc4j-common-tool的测试用例都可以成功，这意味这mpc4j-native-tool的功能是对的。如果其他-s2pc-的文件有类似的错误，我理解应该是其他-s2pc-的测试用例没有自动成功链接到动态库。你可以查看是否按照readme.md下的Demonstration配置了configuration templates。

如果想知道是否配置成功，在上例中，可以点击右上角右箭头左边的SingleZ2cTest，在下拉菜单中选择Edit Configurations...，然后查看Build and run下方是否有类似-ea -Djava.library.path=/mpc4j路径/mpc4j-native-tool/cmake-build-release:/mpc4j路径/mpc4j/mpc4j-native-fhe/cmake-build-release。

**Comment by zhangyingjie7** [comment]
您好，
我应该是配置了
![image](https://github.com/alibaba-edu/mpc4j/assets/24225846/d415381c-480e-42c1-b0a9-3339dac9ba6c)
不知道这样配置是否有问题？

mpc4j-common-tool的测试用例可以成功，以BenesNetworkTest为例，
![image](https://github.com/alibaba-edu/mpc4j/assets/24225846/dbbc9f99-6b72-446d-941e-710298faff6c)

**Comment by liuweiran900217** [comment]
可否邮件我一个会议地址（例如腾讯会议）？我可能需要远程看一下原因。

**Comment by zhangyingjie7** [comment]
您好，
腾讯会议：662-196-370

**Comment by zhangyingjie7** [comment]
感谢刘老师，问题已解决。

To solve the problem,
First, compile mpc4j-native-fourq
```
cd mpc4j-native-fourq
mkdir cmake-build-release
cd cmake-build-release
cmake ..
make
```
Then, recompile mpc4j-native-tool

**Comment by liuweiran900217** [comment]
我们更新了README，提示用户需要正确安装`mpc4j-common-fourq`，还请确定改动是否已经解决此问题，如无问题，我将关闭此issue。

**Comment by zhangyingjie7** [comment]
> 我们更新了README，提示用户需要正确安装`mpc4j-common-fourq`，还请确定改动是否已经解决此问题，如无问题，我将关闭此issue。

已解决
